# Generated by Django 4.2.16 on 2024-10-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
