# Generated by Django 4.2.16 on 2024-11-04 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_back', '0002_useritem_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
