# Generated by Django 4.2.16 on 2024-10-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_back', '0003_rename_description_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
