# Generated by Django 4.2.16 on 2024-10-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_back', '0005_user_remove_item_author_item_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_back.user'),
            preserve_default=False,
        ),
    ]
