name: Django CI

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      working-directory: /home/runner/work/Task/Task/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: /home/runner/work/Task/Task/backend
      run: |
        python manage.py test
