name: Flutter CI

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v4.2.1

    - name: setup java
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: setup flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: '3.24.3'

    - run: flutter pub get
      working-directory: /home/runner/work/Task/Task/frontend
    - run: flutter build apk --release
      working-directory: /home/runner/work/Task/Task/frontend
